"""first_migration

Revision ID: 534e7d6cd031
Revises: 
Create Date: 2024-05-07 21:01:14.066677

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "534e7d6cd031"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("short_link", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_links_link"), "links", ["link"], unique=True)
    op.create_index(
        op.f("ix_links_short_link"), "links", ["short_link"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_links_short_link"), table_name="links")
    op.drop_index(op.f("ix_links_link"), table_name="links")
    op.drop_table("links")
    # ### end Alembic commands ###
