"""change_links_collumns

Revision ID: 90b9bf730aa0
Revises: 534e7d6cd031
Create Date: 2024-05-12 20:12:07.482178

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "90b9bf730aa0"
down_revision = "534e7d6cd031"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("links", sa.Column("source_link", sa.String(), nullable=False))
    op.add_column(
        "links",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.drop_index("ix_links_link", table_name="links")
    op.drop_index("ix_links_short_link", table_name="links")
    op.create_index(op.f("ix_links_source_link"), "links", ["source_link"], unique=False)
    op.create_unique_constraint(None, "links", ["short_link"])
    op.drop_column("links", "link")
    op.drop_column("links", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "links",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "links",
        sa.Column("link", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "links", type_="unique")
    op.drop_index(op.f("ix_links_source_link"), table_name="links")
    op.create_index("ix_links_short_link", "links", ["short_link"], unique=True)
    op.create_index("ix_links_link", "links", ["link"], unique=True)
    op.drop_column("links", "created_at")
    op.drop_column("links", "source_link")
    # ### end Alembic commands ###
